### ISSUE TITLE
safeTransferReward now fails silently if there are not enough tokens to pay out the reward - need to find a better solution

### ISSUE THREAD

**Issue by lirona** [hats-finance/hats-contracts#127]
at the moment if there are not enough HAT tokens to transfer the whole requested reward, the function transfers the available amount and finishes. Should fail and not transfer any tokens in this case (or update user's rewardDebt so that she gets the rest next time it's possible)

**Comment by lirona** [comment]
change the event

**Comment by jellegerbrandy** [comment]
So here is an alternative type of solution.
The problem we have is that rewards cannot be paid out because the HATs balance is insufficient to pay out the amount... instead of waiting for that to happen, we can "fail" earlier -namely when we call `updatePool`, when we calculate the rewardPErShare we also take into account the available of HATs to paya that reward. I.e. if we set the `rewardPerShare` value in such a way tha `rewardPerShare * totalShares <= hatsBalance`

**Comment by jellegerbrandy** [comment]
This last solution will not work, what we need is an equation of the type `rewardPerShare * totalShares <= hatsBalance + hatsPaidOut`, which would require a `hatsPaidOut` counter. It also has the drawback that not all pools are treated equally.

**Comment by jellegerbrandy** [comment]
It seems to me thsi was was also a problem in the v1 version of HatVaults (which fails silently if there are not enough tokens to pay out the reward)
The original pancakeswap implementation https://github.com/pancakeswap/pancake-farm/blob/master/contracts/MasterChef.sol#L222 does not have a limit on minting, I think, so does not have the probelm)
By way of solutions, I see the following:
1- we do what we do now, namely "fail silently" and simply stop paying the rewards to users on withdrawal and deposit (they have no way to recover that)
2- we add more bookkeeping, for example a counter saying how much rewards we already ahve paid out, so we can manage the reward program
3- we can actually throw an error when rewards cannot be paid out on deposit and reward (so users can only emergenyWithdraw)

At this point, I would be for (3). The reasoning here is that this is a real error: HAts is responsible for funding the contract with enough HATs to pay out the rewards, if it does not, then governance either needs to provide enough HATs, or otherwise change the reward program (i.e. call setRewardMultiplier) so that it is not promised too much
