### ISSUE TITLE
shares logic will fail if paid out bounty of 100%

### ISSUE THREAD

**Issue by lirona** [hats-finance/hats-contracts#208]

**Comment by ben-kaufman** [comment]
After #276 vault which paid 100% as claim reward will have deposits revert. One way to fix that is make the max bounty 9999 instead of 10000. Another option is to do nothing, and in such case a vault would still be able to recover by anyone sending vault tokens directly to the vault (not depositing just sending to the vault address).

I guess the first option is better. What do you think?

**Comment by ben-kaufman** [comment]
cc @jellegerbrandy @shayzluf

**Comment by jellegerbrandy** [comment]
What happens if very small value is left? Say 1 wei and  1e24 shares?

**Comment by ben-kaufman** [comment]
Well if there's 1 wei and 2 depositors, the 1 way will be spliced between the 2 of them so no one can redeem it (too small to split). But if there is 1 wei and 1 depositor that depositor can redeem it by redeeming all their shares.

**Comment by ben-kaufman** [comment]
But even if there is just 1 wei in the contracts deposits will be possible

**Comment by ben-kaufman** [comment]
Basically there can be a rounding error up to the number of different depositors. If for example there are 3 depositors and just 1 wei, no one can redeem. If there are 3 depositors and 5 wei, they can redeem up to 1 wei (unless someone overturns shares with the redeem function)

**Comment by ben-kaufman** [comment]
Ok so we decided to limit payout to 90%
