### ISSUE TITLE
Add upgrade behind Timelock of four weeks 

### ISSUE THREAD

**Issue by jellegerbrandy** [hats-finance/hats-contracts#249]

**Comment by jellegerbrandy** [comment]
This can either be done by:
- changing the HAts timelockcontroller
- add a new timelockcontroller (and a new role)
- implement the logic in the hatvaults.sol

**Comment by ben-kaufman** [comment]
So in terms of extra code changes I think a new role and new tome lock controller is the simplest solution which requires the least changes. The second simplest solution would be to edit the hats timelockcontroller to have some internal extra timelock on this. About implementing on the hats vaults it's a bit problematic since the hats vaults itself is not aware of the proxy contract, it is the implementation contract...

**Comment by ben-kaufman** [comment]
Closing as we remove upgradeability
