### ISSUE TITLE
Can we remove the whitelist for the routers?

### ISSUE THREAD

**Issue by jellegerbrandy** [hats-finance/hats-contracts#289]

**Comment by ben-kaufman** [comment]
So the reasoning is that in the past the vault funds were all together in one contract with the funds to swap, so all those funds were at risk, and we needed a way to have a delay before such approval so users might withdraw their funds from the vaults. But now since the vault funds are separate we don't need this protection anymore.

**Comment by jellegerbrandy** [comment]
Also other reasoning:
- having uniswap3 hardcoded as the place to trade tokens is not flexible enough to support all tokens/other chains
- there were "attacks" that governance could do anyway, stealing some tokens, by playing with uniswap paths and liquidity
