### ISSUE TITLE
depositPause is not pausing deposits

### ISSUE THREAD

**Issue by jellegerbrandy** [hats-finance/hats-contracts#296]
As far as I can see, setting `depositPause` has no effect at all. 

We should pause deposits, and probably also transfers, so perhaps it can be checked in _beforeTokenTransfer()

While we are at it, also make the param name consistent (it is called `_isPaused` in createVault and `depositPause` in `setDepositPause`. Let's call it `_isPaused` also there.

**Comment by ben-kaufman** [comment]
This isn't exactly true, depositPause does pause deposits, because it changes the maxMint and maxDeposit to 0, which then affects the deposit and mint functions in the ERC4626 code. We have a test that ensures this.
It's true transfers are still allowed, but not sure if we are supposed to disable it? It only moves existing funds not adds new funds to the vault.

About the naming I agree.
